### ISSUE TITLE
Change title to include "UK" or "British"

### ISSUE THREAD

**Issue by neilb** [davorg/succession#22]
Instead of "Line of Succession", maybe "British Monarch: Line of Succession", or just "British Line of Succession"?

**Comment by davorg** [comment]
Used "British" as I plan to go back beyond the start of the UK.

**Comment by neilb** [comment]
You didn't add "British" to the menu bar.

**Comment by davorg** [comment]
No idea what you mean. It's there. Of course it's there. It's always been there. We have always been at war with Eurasia.

;-/

**Comment by neilb** [comment]
Hey, no gaslighting!
