### ISSUE TITLE
Show a history of person's titles.

### ISSUE THREAD

**Issue by davorg** [davorg/succession#25]

**Comment by ras52** [comment]
Is the idea that if I look at the [line of succession in 1950](https://lineofsuccession.co.uk/1950-01-01) I should see "Prince Charles of Edinburgh"; [after his mother's accession in 1952](https://lineofsuccession.co.uk/1952-02-06) I should see "Prince Charles, Duke of Cornwall"; and from 26 July 1958 onwards, he should be "Prince Charles, Prince of Wales"?

**Comment by davorg** [comment]
That's exactly right. The database already supports time-base names and titles, but currently, I have only input date for the monarchs. You'll see, for example, how the queen's title changes through time.

Adding this data for all of the people in the database is going to be a big task.

**Comment by ras52** [comment]
Ah, yes.  I see you have the Queen as:
* Princess Elizabeth of York  (1926-04-21 to 1936-12-10)
* The Princess Elizabeth (1936-12-11 to 1947-11-19)
* The Princess Elizabeth, Duchess of Edinburgh (1947-11-20 to 1952-02-05)
* Queen Elizabeth II (1952-02-06 to present)

Where do you stand on the use of styles like HRH and HM?  One other point is that the style "Queen Elizabeth II" is slightly inconsistent with what you do with foreign monarchs, e.g. "Harald V, King of Norway".  Should it be "Elizabeth II, Queen of Great Britain and Northern Ireland" or similar?

**Comment by davorg** [comment]
I'm ignoring "HRH", etc. I may rethink that later.

I value clarity over consistency. I'm aiming to use names and titles that most people will recognise. I might change the Norwegians to something like "King Harald V of Norway". I think the country is only necessary if it isn't the UK.
