### ISSUE TITLE
how to contribute data?

### ISSUE THREAD

**Issue by szabgab** [davorg/succession#26]
It would be nice to have some document explaining how and where to contribute data?

**Comment by davorg** [comment]
Currently I'm at the level of "send me whatever you have in whatever format you like and I'll make it work somehow" :-)

**Comment by szabgab** [comment]
Would it be possible, interesting, etc. to have all the data in csv or JSON format in GitHub and load it from there? That way people could contribute data by sending you PRs.

**Comment by davorg** [comment]
To be honest, I'm expecting most fixes to come from historians and genealogists - who (mostly) won't want to send Github patches. But, sure, I'll think about including the data in a more readable format. Currently, the live data dump is in https://github.com/davorg/succession/blob/master/data/succession.dump
