### ISSUE TITLE
Marriage of Catholics

### ISSUE THREAD

**Issue by ras52** [davorg/succession#36]
Under the [Act of Settlement (1701)](https://en.wikipedia.org/wiki/Act_of_Settlement_1701), a person who marries a Catholic is excluded from the succession.  This was repealed by the [Succession to the Crown Act (2013)](https://en.wikipedia.org/wiki/Succession_to_the_Crown_Act_2013) which came into effect on [26th March 2015](http://www.legislation.gov.uk/uksi/2015/894/made) which reinstated those who had married Catholics to the line of succession (but not those who converted to Catholicism).

In recent times this has affected two people: [Prince Michael of Kent](https://en.wikipedia.org/wiki/Prince_Michael_of_Kent) who married a Catholic on 30 June 1978, and [George Windsor, Earl of St Andrews](https://en.wikipedia.org/wiki/George_Windsor,_Earl_of_St_Andrews) who married a Catholic on  9th January 1988.  From these dates until 26th March 2015 they were therefore excluded from the line of succession, however both are [currently listed](https://lineofsuccession.co.uk/?date=1988-01-10) on the site.

**Comment by ras52** [comment]
Note that although a person who married a Catholic was excluded from the succession (until 2015), if they did not convert to Catholicism their children remained in the line of succession.  Thus, even though Prince Michael was out of the line of succession, his children Lord Frederick and Lady Gabriella both remained in the line of succession.

**Comment by ras52** [comment]
[Haakon Lorentzen](https://no.wikipedia.org/wiki/Haakon_Lorentzen), son of Princess Ragnhild of Norway, and who was [briefly on the top 20](https://lineofsuccession.co.uk/1960-01-01) in the late 1950s and early '60s married a Catholic on 14th April 1982, though by this time he was well out of the top 20.  (Source: Marlene Eilers, *Queen Victoria's Descendants* (1987).)

**Comment by davorg** [comment]
Yes, I know about this problem. I think it is going to need a change to the data model. I need to support people who marry Catholics and also people who convert to (and, I suppose, from) Catholicism. I hope to get to this at some point this week.

**Comment by ras52** [comment]
I don't think conversion from Catholicism is relevant.  Catholics are considered "naturally dead" for the purpose of succession, and this excludes you forever.  If you convert away from Catholicism, it's too late to put you back into the line of succession.  The [Bill of Rights](https://www.legislation.gov.uk/aep/WillandMarSess2/1/2/introduction), which is still in effect today, says (my emphasis):

> That all and every person and persons that is are or shall be reconciled to or shall hold Communion 
> with the See or Church of Rome or shall professe the Popish Religion ... shall be excluded and be 
> **for ever** uncapeable to inherit possesse or enjoy the Crowne

**Comment by davorg** [comment]
Oh, that's interesting. Thanks; I didn't know that.

I imagine that's a possible contender for reform in the future.

**Comment by ras52** [comment]
I can imagine it may be changed in the not too distant future, though allowing Catholics or ex-Catholics is sometimes seen as being incompatible with the sovereign's position as Supreme Governor of the Church of England and the title "Defender of the Faith".  I think this may change quite rapidly after the Queen's death.  But for the moment, this is a good thing for the purpose of this project, as there's no need to look any further once someone converts to Catholicism or is raised as one.

**Comment by davorg** [comment]
Right. This is now implemented.

* https://lineofsuccession.co.uk/1978-06-29 (Prince Michael of Kent is at 16)
* https://lineofsuccession.co.uk/1978-06-30 (Prince Michael of Kent is gone)

Next step: Add more exclusion data (i.e. people who either married a Catholic, became Catholic or were born illegitimate.
