### ISSUE TITLE
Gerald Lascelles is missing

### ISSUE THREAD

**Issue by ras52** [davorg/succession#37]
*This was reported by Chris Pitt Lewis on the soc.genealogy.britain newsgroup.*

[The Hon. Gerald Lascelles](https://en.wikipedia.org/wiki/Gerald_David_Lascelles), younger son of Princess Mary, Princess Royal and Countess of Harewood, and a grandson of George V is [missing](https://lineofsuccession.co.uk/?date=1930-01-01).  His eldest son, Henry Lascelles, who was in the top twenty in the line of succession during the 1950s, is also missing.

Also, the surname of his brother, George Lascalles [sic] is misspelt.  It should be Lasc**e**lles.

**Comment by ras52** [comment]
Note that Gerald's younger son, Martin Lascelles, was born before Gerald's marriage to Martin's mother (Gerald's second wife), so Martini is illegitimate and excluded from the succession, just as Gerald's brother George's youngest son Mark Lascelles was.

**Comment by davorg** [comment]
Thanks. Fixed.
