### ISSUE TITLE
Order of the daughters of Princess Louise, Princess Royal and Duchess of Fife

### ISSUE THREAD

**Issue by ras52** [davorg/succession#38]
*This was reported by Chris Pitt Lewis on the soc.genealogy.britain newsgroup.*

[Princess Louise, Princess Royal and Duchess of Fife](https://en.wikipedia.org/wiki/Louise,_Princess_Royal) had two daughter.  The eldest was [Princess Arthur of Connaught and Strathearn, 2nd Duchess of Fife](https://en.wikipedia.org/wiki/Princess_Alexandra,_2nd_Duchess_of_Fife); the youngest was [Princess Maud, Countess of Southesk](https://en.wikipedia.org/wiki/Princess_Maud,_Countess_of_Southesk).  They are in the [wrong order](https://lineofsuccession.co.uk/?date=1901-01-22) on the site, though their dates of births are given correctly.

**Comment by davorg** [comment]
Thanks. Fixed
