### ISSUE TITLE
Order of the children of King Olav V of Norway

### ISSUE THREAD

**Issue by ras52** [davorg/succession#39]
[King Olav V of Norway](https://en.wikipedia.org/wiki/Olav_V_of_Norway) had three children: Princess Ragnhild, Princess Astrid and the future Harald V.  They all appear on the site with the correct dates of birth, but they are [listed in chronological order](https://lineofsuccession.co.uk/1952-02-06), rather than listing Harald V ahead of his sisters due to male-preference primogeniture.

Also, Olav V should probably be labelled "Olaf V, King of Norway" just as Harald V is labelled "Harald V, King of Norway".

**Comment by davorg** [comment]
Thanks. Fixed.

**Comment by ras52** [comment]
Olav V has lost his regnal number: he's just "Olaf, King of Norway" [on the site currently](https://lineofsuccession.co.uk/1952-02-06).

**Comment by davorg** [comment]
Oops. I shouldn't dabble in databases so early in the morning. Fixed now. Thanks.
