### ISSUE TITLE
Names for distant relationships

### ISSUE THREAD

**Issue by ras52** [davorg/succession#41]
Xan Windsor, Lord Culloden is [described on the site](https://lineofsuccession.co.uk/2007-03-12) as "4/2 of the sovereign".  He is in fact Elizabeth II's *first cousin twice removed*.  I think I've seen a 4/3 somewhere too, though I can't now find it.

**Comment by davorg** [comment]
Thanks. I didn't realise that such remote relationships were appearing on the site. Fixed now.
