### ISSUE TITLE
Time-based titles for Elizabeth II's descendants

### ISSUE THREAD

**Issue by ras52** [davorg/succession#43]
Issue #14 is to add data for time-based titles for everyone in the database.  This will be time consuming to do in full, but here's a summary of the data for Elizabeth II's descendants.

Before Elizabeth's accession (1952-02-06) her two children were
* Prince Charles of Edinburgh
* Princess Anne of Edinburgh

On the day of Elizabeth's accession they lost their territorial designation and became *The* Prince or Princess *N*; as they were born, her younger sons had similar styles.  Charles, as heir apparent, became Duke of Cornwall automatically. 
* The Prince Charles, Duke of Cornwall  (officially he was simply styled The Duke of Cornwall, but I imagine you want to include his name too - see my comment in #14)
* The Princess Anne
* The Prince Andrew
* The Prince Edward

They all gained another title over time.
* The Prince Charles, Prince of Wales (from 1958-07-26)
* The Princess Anne, Princess Royal (from 1987-06-13)
* The Prince Andrew, Duke of York (from 1986-07-23)
* The Prince Edward, Earl of Wessex (from 1999-06-19)

I'm guessing you probably don't want to include the style "The Princess Anne, Mrs Mark Phillips", as she was from her marriage until she became Princess Royal.  It sounds horribly dated to me, and I don't recall it ever being used, e.g. by the press, at the time.

At birth, Charles children had the style
* Prince William of Wales
* Prince Henry of Wales

William now has a dukedom, and we can expect similar for Harry later this year:
* Prince William, Duke of Cambridge (from 2011-04-29)

The children of Prince Andrew and Prince Edward have not changed their styles.  

Zara Phillips became Zara Tindall on 2011-07-30.

**Comment by davorg** [comment]
Thanks. This is useful.

**Comment by ras52** [comment]
By the looks of things, all of George VI's descendants have been done too and good progress is being made towards completing George V's.

**Comment by davorg** [comment]
Yep. I've been on a bit of a roll this evening :-)
