### ISSUE TITLE
Feature suggestion: show change on date of change

### ISSUE THREAD

**Issue by ras52** [davorg/succession#52]
If I look at the list of succession on one of dates when if changed (e.g. 1926-04-21 when the Queen was born), could you perhaps highlight what changed that day?  On that particular date you could somehow highlight entry 3 on the list as a new entry.  On other days you might need to show a person who died that day without a numbered place in the succession and somehow indicate that they died that day.

One way of indicating it might be to give both the number of each person at the start of the day and at the end of the day.  (Though I don't think you can do that with an `<ol>` in HTML.)

**Comment by davorg** [comment]
It's certainly something I've considered. I'll give it some thought over the weekend.

**Comment by banng** [comment]
+1 for this, I came here to suggest it.
Could you have a one-line description of the change on any date, eg "X was born", "Y was made Duke of Earl", or "the rule changed about male precedence"?

**Comment by davorg** [comment]
Done. See, for example https://lineofsuccession.co.uk/2019-05-06
