### ISSUE TITLE
Feature suggestion: show date of previous and subsequent changes

### ISSUE THREAD

**Issue by ras52** [davorg/succession#53]
If I look at the list of succession on a particular date (e.g. 2000-01-01), it would be nice to know the period during which the list was correct.  In this case, it began on 1999-07-01 with the birth of Charles Armstrong-Jones and lasted until the birth of Eloise Taylor on 2003-03-02.

**Comment by davorg** [comment]
I think did that yesterday, with the addition of the previous/next change links.

**Comment by ras52** [comment]
Oh, sorry.  I wrote this feature request yesterday morning but realised I hadn't pressed 'submit' until late last night.  I didn't think to check you hadn't done it in the mean time!  Mea culpa.

**Comment by davorg** [comment]
No need to apologise. It's great to know I'm adding features that people actually want :-)
