### ISSUE TITLE
Princess Alexandra's grandchildren missing

### ISSUE THREAD

**Issue by ras52** [davorg/succession#54]
Now that the site lists the top 30 in the line of succession, Princess Alexandra's grandchildren need including.

* James Robert Bruce Ogilvy (b 1964-02-29)
* * Alexander Charles Ogilvy (b 1996-11-12)
* * Flora Alexandra Ogilvy (b 1994-12-15)
* Marina Victoria Alexandra Ogilvy (b 1966-07-31)
* * Christian Alexander Mowatt (b 1993-06-04)
* * Zenouska May Mowatt (b 1990-05-26)

Note that Marina Ogilvy married on 1990-02-02 taking the surname Mowatt, and reverted to the surname Ogilvy around the time of her divorce (1997-10-15).

*Source: [Princess Alexandra's article of Wikipedia](https://en.wikipedia.org/wiki/Princess_Alexandra,_The_Honourable_Lady_Ogilvy).*

**Comment by davorg** [comment]
Thanks for this and all the other comments you made overnight. I'm going to be away from computers for the next three days, but I'll pick up your suggestions early next week.

**Comment by davorg** [comment]
Ok. I found time to do this before leaving.

Seem to me that the press still refers to Marina by her married name. Do you have a reference saying that's wrong?

**Comment by ras52** [comment]
I thought I had a reference to Marina reverting to Ogilvy, though I can't immediately recall what; but you're right, the press do still seem to refer to her by her married surname. Probably best to do that.
