### ISSUE TITLE
Add all descendants of George III

### ISSUE THREAD

**Issue by davorg** [davorg/succession#9]

**Comment by ras52** [comment]
This job is much simpler than the corresponding one (#8) for Queen Victoria, and I think it would be quick to do legitimate descendants down to the great great grandchildren.

George III had fifteen children, but only six legitimate grandchildren who lived to adulthood:
* Princess Charlotte of Wales.  Died in childbirth without surviving issue.
* Queen Victoria.  Already covered.
* King George V of Hanover.  Three children and seven grandchildren.
* Prince George, Duke of Cambridge.  Married in contravention of the Royal Marriages Act.
* Princess Augusta, Grand Duchess of Mecklenburg-Strelitz.  One son and four grandchildren.
* Princess Mary, Duchess of Teck.  Four children, but only four grandchildren who were not descended from Queen Victoria.

**Comment by davorg** [comment]
Done
